spring.application.name=WolkAndHold

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.show-sql=true

logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.socket=DEBUG
